language: python
python:
  - "2.6"
  - "2.7"

notifications:
  email:
      - alexprengere@gmail.com

# command to install dependencies
install:
    - "python setup.py install --user"

# command to run tests
script: "python tests/test_formalsystems.py -v"
